# Generated by Django 3.2.15 on 2022-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('uaddress', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=30)),
            ],
        ),
    ]
