# Generated by Django 3.2.15 on 2022-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='ugender',
            field=models.CharField(default='other', max_length=10),
        ),
    ]
