# Generated by Django 3.2.14 on 2022-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20221007_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
