# Generated by Django 3.2.14 on 2023-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230105_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=20),
        ),
    ]
